In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [48]:
#import data
from sklearn.datasets import load_iris
from sklearn.preprocessing import MinMaxScaler, RobustScaler, StandardScaler, KBinsDiscretizer
#load the iris dataset
iris = load_iris()
X = iris.data

In [27]:
Minimum = -1
Maximum = 1

In [20]:
#create instance for minmaxscaler
scaler = MinMaxScaler(feature_range=(Minimum,Maximum))
scaled_data = scaler.fit_transform(X)

In [21]:
#Original data
X[:5]


array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [22]:
#Scaled data
scaled_data[:5]

array([[0.22222222, 0.625     , 0.06779661, 0.04166667],
       [0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [0.11111111, 0.5       , 0.05084746, 0.04166667],
       [0.08333333, 0.45833333, 0.08474576, 0.04166667],
       [0.19444444, 0.66666667, 0.06779661, 0.04166667]])

In [29]:
#Feature scaling
rob_scaler = RobustScaler()

#Fit and transform the data
robust_data = rob_scaler.fit_transform(X)


In [30]:
robust_data[:5]

array([[-0.53846154,  1.        , -0.84285714, -0.73333333],
       [-0.69230769,  0.        , -0.84285714, -0.73333333],
       [-0.84615385,  0.4       , -0.87142857, -0.73333333],
       [-0.92307692,  0.2       , -0.81428571, -0.73333333],
       [-0.61538462,  1.2       , -0.84285714, -0.73333333]])

In [32]:
#Feature clippin
#set up range
min_clip=0
max_clip=2
#clip the fatures
clipped_features = np.clip(X,min_clip,max_clip)

In [33]:
X[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [34]:
clipped_features[:5]

array([[2. , 2. , 1.4, 0.2],
       [2. , 2. , 1.4, 0.2],
       [2. , 2. , 1.3, 0.2],
       [2. , 2. , 1.5, 0.2],
       [2. , 2. , 1.4, 0.2]])

In [35]:
#log scaling
log_scaled = np.log(X)
log_scaled[:5]

array([[ 1.62924054,  1.25276297,  0.33647224, -1.60943791],
       [ 1.58923521,  1.09861229,  0.33647224, -1.60943791],
       [ 1.54756251,  1.16315081,  0.26236426, -1.60943791],
       [ 1.5260563 ,  1.13140211,  0.40546511, -1.60943791],
       [ 1.60943791,  1.28093385,  0.33647224, -1.60943791]])

In [43]:
#Z-score /standard scaler
std_scaler = StandardScaler()
## fit and transford the data
scaler_Z = std_scaler.fit_transform(X)

scaler_Z[:5]


array([[-0.90068117,  1.01900435, -1.34022653, -1.3154443 ],
       [-1.14301691, -0.13197948, -1.34022653, -1.3154443 ],
       [-1.38535265,  0.32841405, -1.39706395, -1.3154443 ],
       [-1.50652052,  0.09821729, -1.2833891 , -1.3154443 ],
       [-1.02184904,  1.24920112, -1.34022653, -1.3154443 ]])

In [55]:
## Bucketing
data= pd.DataFrame(iris.data, columns=iris.feature_names)

#create buckets
number_buckets = 10

#intalise the instance of the KBinsDiscretizer
dis = KBinsDiscretizer(n_bins=number_buckets, encode='ordinal', strategy='uniform')

##fit transform the data
trans_dis = pd.DataFrame(dis.fit_transform(data),columns = data.columns)
trans_dis.head()

c:\Users\T\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\preprocessing\_discretization.py:248: FutureWarning: In version 1.5 onwards, subsample=200_000 will be used by default. Set subsample explicitly to silence this warning in the mean time. Set subsample=None to disable subsampling explicitly.
  warnings.warn(


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                2.0               6.0                0.0               0.0
1                1.0               4.0                0.0               0.0
2                1.0               5.0                0.0               0.0
3                0.0               4.0                0.0               0.0
4                1.0               6.0                0.0               0.0

In [56]:
trans_dis.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
dtypes: float64(4)
memory usage: 4.8 KB


In [54]:
data

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [58]:
## Bucketing quanile boundaries
data= pd.DataFrame(iris.data, columns=iris.feature_names)

#create buckets
number_buckets = 5

#intalise the instance of the KBinsDiscretizer
dis = KBinsDiscretizer(n_bins=number_buckets, encode='ordinal', strategy='quantile')

##fit transform the data
trans_dis = pd.DataFrame(dis.fit_transform(data),columns = data.columns)
trans_dis.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                1.0               4.0                0.0               1.0
1                0.0               2.0                0.0               1.0
2                0.0               3.0                0.0               1.0
3                0.0               3.0                1.0               1.0
4                1.0               4.0                0.0               1.0

In [63]:
new_data = pd.DataFrame({'DateTime':['2024-01-01 10:30:00','2024-10-01 12:30:59']})
#convert to date time
new_data['DateTime']=pd.to_datetime(new_data['DateTime'])

#split date time
new_data['year']=new_data['DateTime'].dt.year
new_data['month']=new_data['DateTime'].dt.month
new_data['day']=new_data['DateTime'].dt.day
new_data['day_name']=new_data['DateTime'].dt.day_name()
new_data['hour']=new_data['DateTime'].dt.hour


In [64]:
print(new_data)

             DateTime  year  month  day day_name  hour
0 2024-01-01 10:30:00  2024      1    1   Monday    10
1 2024-10-01 12:30:59  2024     10    1  Tuesday    12


In [66]:
X = pd.DataFrame(iris.data,columns=iris.feature_names)


In [72]:
#featue selection
corr_mat=X.corr().abs()
#create a matrix with the same shape of the corr mat
mask = np.triu(np.ones_like(corr_mat,dtype=bool))

mask_df =corr_mat.mask(mask)
mask_df

sepal length (cm)  sepal width (cm)  petal length (cm)  \
sepal length (cm)                NaN               NaN                NaN   
sepal width (cm)            0.117570               NaN                NaN   
petal length (cm)           0.871754          0.428440                NaN   
petal width (cm)            0.817941          0.366126           0.962865   

                   petal width (cm)  
sepal length (cm)               NaN  
sepal width (cm)                NaN  
petal length (cm)               NaN  
petal width (cm)                NaN

In [73]:
drop_it = [c for c in mask_df.columns if any(mask_df[c]>0.95)]
drop_it

['petal length (cm)']

In [83]:
from sklearn.decomposition import PCA

#Create instance 
pca= PCA(n_components=4)
X_pca = pca.fit_transform(X)

In [84]:
X_pca[:5]

array([[-2.68412563e+00,  3.19397247e-01, -2.79148276e-02,
        -2.26243707e-03],
       [-2.71414169e+00, -1.77001225e-01, -2.10464272e-01,
        -9.90265503e-02],
       [-2.88899057e+00, -1.44949426e-01,  1.79002563e-02,
        -1.99683897e-02],
       [-2.74534286e+00, -3.18298979e-01,  3.15593736e-02,
         7.55758166e-02],
       [-2.72871654e+00,  3.26754513e-01,  9.00792406e-02,
         6.12585926e-02]])

In [85]:
## print ratio to verify
pca.explained_variance_ratio_

array([0.92461872, 0.05306648, 0.01710261, 0.00521218])