In [4]:
import numpy as np



[1 2 3]


In [6]:
#1-dimentiaonal array 1x3, [1,2,3]:

my1dArray = np.array([1,2,3])

print(my1dArray)

[1 2 3]


In [5]:
#2-dimentiaonal array 2x3, [1,2,3]:
my2dArray = np.array([[1,2,3],[4,5,6]])
print(my2dArray)

[[1 2 3]
 [4 5 6]]


In [7]:
my1dArray.dtype

dtype('int32')

In [8]:
my2dArray.dtype

dtype('int32')

In [12]:
## specifiying hte data type
my2dArrayfloat = np.array([[1,2,3],[4,5,6]], dtype=np.float32)
print(my2dArrayfloat)

[[1. 2. 3.]
 [4. 5. 6.]]


In [13]:
my2dArrayfloat.dtype

dtype('float32')

In [16]:
# NumPy fundamentals
#combination of intiger and string
charArray1 = np.array([(1,'a',3),(4, 5, 'zzz')])

print(charArray1)
charArray1.dtype

[['1' 'a' '3']
 ['4' '5' 'zzz']]


dtype('<U11')

In [20]:
#Numpy array initialisation
number_rows = 2
number_columns = 3

## array of zeros
array0s = np.zeros((number_rows, number_columns), dtype=np.int32)
print(array0s)

[[0 0 0]
 [0 0 0]]


In [28]:
## array of zeros
array0s = np.zeros((3, 5), dtype=np.int32)
print(array0s)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [38]:
## array of ones
array1s = np.ones((3, 5), dtype=np.int32)
print(array1s)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [40]:
## array of fives
array5s = 4 + np.ones((3, 5), dtype=np.int32)
print(array5s)
array5s.dtype

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


dtype('int32')

In [42]:
## Array of sevens
array7s = np.full((number_rows,number_columns), 7)
print(array7s)
array7s.dtype

[[7 7 7]
 [7 7 7]]


dtype('int32')

In [50]:
##Array of evenly spaced values
start= 10
end= 27  ### last number gets ignored
step= 3
evenlystep= np.arange(start, end, step)
print(evenlystep)

[10 13 16 19 22 25]


In [52]:
## this is generating equally spaced numbers
number_samples = 4
evenlysample = np.linspace(start,end,number_samples)
print(evenlysample)
evenlysample.dtype

[10.         15.66666667 21.33333333 27.        ]


dtype('float64')

In [55]:
#identity matrix between 0 an 1
identity = np.eye(4)
print(identity)
identity.dtype

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


dtype('float64')

In [64]:
# generate floating numbers between 0 and 1 (1 not included)using random
random01=np.random.random((4, 6))
print(random01)
random01.dtype

[[0.2122983  0.46461137 0.00363528 0.99290716 0.77842269 0.46658012]
 [0.49726152 0.54771961 0.28256926 0.94149037 0.01946548 0.86659848]
 [0.54380387 0.85906973 0.23237332 0.71339554 0.55492382 0.30549793]
 [0.99395567 0.41790268 0.8267948  0.62764078 0.23345755 0.96731656]]


dtype('float64')

In [66]:
##random.randint
#print int numbers specified with last value not inclusive 
randomintRange = np.random.randint(0,11,(2,3))
print(randomintRange)

[[ 3  5 10]
 [ 2  8  3]]


In [69]:
#NumPy Array inspection, indexing and slicing
a = np.array([[5,6,3], [2,5,1]])
print(a)
print('a has dimension: ', a.ndim)
print('a has shape: ', a.shape)
print('a has size: ', a.size)
print('a has data type: ', a.dtype)



[[5 6 3]
 [2 5 1]]
a has dimension:  2
a has shape:  (2, 3)
a has size:  6
a has data type:  int32


In [71]:
##indexing arrays
print(a[0,2])

3


In [78]:
## indexing multiple values
a[1,:2]

array([2, 5])

In [79]:
np.diag(a)

array([5, 5])

In [81]:
b=np.array([[5,6,3],[2,5,1],[4,4,4]])
print(b)

[[5 6 3]
 [2 5 1]
 [4 4 4]]


In [82]:
np.diag(b)

array([5, 5, 4])

In [87]:
#inverse diagonal
np.diag(np.fliplr(b))


array([3, 5, 4])

In [89]:
arr = np.array([0,2,4,5,3,7,8,9,5,1])

for i in range(len(arr)):
    if arr[i] % 2 ==1:
        arr[i] = -arr[i]

print(arr)


[ 0  2  4 -5 -3 -7  8 -9 -5 -1]


In [90]:
arr = np.array([0,2,4,5,3,7,8,9,5,1])

odd_num= np.where(arr % 2 == 1)

arr[odd_num] *=-1
print(arr)

[ 0  2  4 -5 -3 -7  8 -9 -5 -1]


In [92]:
a1 = np.array([[1,2,5], [7,1,5]])
a2 = np.array([[4,6,9], [2,5,1]])


In [93]:
#addition
add1 = a1 + a2
add2 = np.add(a1,a2)
print(add1)
print(add2)


[[ 5  8 14]
 [ 9  6  6]]
[[ 5  8 14]
 [ 9  6  6]]


In [95]:
#subtraction
sub1 = a1 - a2
sub2 = np.subtract(a1,a2)
print(sub1)
print(sub2)

[[-3 -4 -4]
 [ 5 -4  4]]
[[-3 -4 -4]
 [ 5 -4  4]]


In [97]:
#multiplication
mul1 = a1 * a2
mul2 = np.multiply(a1,a2)
print(mul1)
print(mul2)

[[ 4 12 45]
 [14  5  5]]
[[ 4 12 45]
 [14  5  5]]


In [98]:
#division
div1 = a1 / a2
div2 = np.divide(a1,a2)
print(div1)
print(div2)

[[0.25       0.33333333 0.55555556]
 [3.5        0.2        5.        ]]
[[0.25       0.33333333 0.55555556]
 [3.5        0.2        5.        ]]


In [100]:
##dot product
a3 = np.array([[4,6],[2,5],[9,1]])
dotp = a1.dot(a3)
print(dotp)

[[53 21]
 [75 52]]


In [101]:
exp = np.exp(a)
sqroot =np.sqrt(a)
sin= np.sin(a)
cos = np.cos(a)
log = np.log(a)

In [102]:
print(exp)

[[148.4131591  403.42879349  20.08553692]
 [  7.3890561  148.4131591    2.71828183]]


In [103]:
print(sqroot)

[[2.23606798 2.44948974 1.73205081]
 [1.41421356 2.23606798 1.        ]]


In [104]:
print(sin)

[[-0.95892427 -0.2794155   0.14112001]
 [ 0.90929743 -0.95892427  0.84147098]]


In [105]:
print(cos)

[[ 0.28366219  0.96017029 -0.9899925 ]
 [-0.41614684  0.28366219  0.54030231]]


In [106]:
print(log)

[[1.60943791 1.79175947 1.09861229]
 [0.69314718 1.60943791 0.        ]]


In [108]:
## NumPy statistics
##Summation
a5 = np.array([[1,2,5],[7,1,3]])
##summation by column
sum1 =a5.sum(axis=1)
sum2 = np.sum(a5, axis=1)
print(sum1)

[8 3 8]


In [109]:
##summation by column
sum1row =a5.sum(axis=0)
sum2row = np.sum(a5, axis=1)
print(sum1row)

[8 3 8]


In [111]:
#maximum 
maxi = a5.max()
maxi2 = a5.max(axis=1)
maxi3= a5.max(axis=0)

print(maxi)
print(maxi2)
print(maxi3)

7
[5 7]
[7 2 5]


In [112]:
#standard deviation
standard_dev = np.std(a5)
print(standard_dev)

2.1921577396609844


In [113]:
## average
avg = np.mean(a5,axis=0)
avg2 = np.mean(a5)
print(avg)
print(avg2)

[4.  1.5 4. ]
3.1666666666666665


In [114]:
#Triangle task
a = np.array([0,0])
b = np.array([0,3])
c = np.array([1.5,0])

from numpy import linalg as la 

ab = la.norm(a-b)
ac = la.norm(a-c)
bc = la.norm(b-c)

In [115]:
#print output of triangle
print(ab)
print(ac)
print(bc)

3.0
1.5
3.3541019662496847


In [116]:
#NumPy array manipulation
a7 = np.array([[1,2,5],[7,1,3]])

#transposing
aTr1 = np.transpose(a7)
aTr2 = a7.T
print(aTr2)

[[1 7]
 [2 1]
 [5 3]]


In [118]:
#Reshape
reshape1 = np.reshape(a7,(3,2))
reshape2 = a7.reshape(3,2)
print(reshape1)
print(reshape2)

[[1 2]
 [5 7]
 [1 3]]
[[1 2]
 [5 7]
 [1 3]]


In [120]:
#reshape to row
reshapeToRow = a7.reshape(6)
print(reshapeToRow)

[1 2 5 7 1 3]


In [121]:
#stacking horizontally
a8 = np.array([[1,2,5],[7,1,3]])
a9 = np.array([[7,8],[4,1]])
a10 = np.array([[9],[9]])

abc=np.hstack([a8,a9,a10])           
print(abc)   

[[1 2 5 7 8 9]
 [7 1 3 4 1 9]]


In [125]:
array1 = np.array([[1,2,3],[4,5,6]])
array2 = np.array([[7,8,9],[10,11,12]])
array3 = np.array([[13,14,15],[16,17,18]])

In [127]:
#vertical stacking
bac = np.vstack([array1, array2, array3])
print(bac)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


In [129]:
#concatenate
ab= np.concatenate((array1, array2, array3), axis=1)
print(ab)

[[ 1  2  3  7  8  9 13 14 15]
 [ 4  5  6 10 11 12 16 17 18]]


In [130]:
#concatenate
ab= np.concatenate((array1, array2, array3), axis=0)
print(ab)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


In [131]:
## save a single array to a file
np.save('array_a',array1)

In [132]:
## save multiple array to a file
np.savez('arrays_ab',arr1 = array1, arr2 = array2)

In [133]:
## save array to a txt file
np.savetxt('array_a.txt',array1)

In [135]:
##delimiter txt file
## %d = intiger format
## %f = float number
## %s = string number
## %.2f = float number ot the nearest 2 decimal place

## fmt = format
np.savetxt('array_a4.txt',array1, delimiter=',', fmt='%f')

In [136]:
## saving to a .csv file
np.savetxt('array_a4.csv',array2, delimiter=',', fmt='%d')

In [137]:
# how to load a .npy and .npz file
# load npy file
le = np.load('array_a.npy')
print(le)

[[1 2 3]
 [4 5 6]]


In [141]:
# load npz file
le2 = np.load('arrays_ab.npz')
print(le2['arr1'])
print(le2['arr2'])

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [149]:
## load txt file
le3 = np.loadtxt('array_a4.txt', delimiter=',')
print(le3)

[[1. 2. 3.]
 [4. 5. 6.]]


In [151]:
##load a csv file
le4 = np.loadtxt('array_a4.csv', delimiter=',')
print(le4)

[[ 7.  8.  9.]
 [10. 11. 12.]]


In [158]:
data1 = np.array([[1.99, 2.23],[5.30,7.75],[1.89,3.01]])

datar = np.around(data1,1)
print(datar)

datas = np.char.mod('%.1f',datar)
print(datas)

row_h = np.array([['r1', 'r2', 'r3']])
column_h = np.array([['c1','c2','c3']])

cSt = np.hstack([column_header,row_header])    
print(cSt)
# np.savetxt('datar.csv', datar, delimiter=',', fmt='%.1f')

[[2.  2.2]
 [5.3 7.8]
 [1.9 3. ]]
[['2.0' '2.2']
 ['5.3' '7.8']
 ['1.9' '3.0']]
[['c1' 'c2' 'c3' 'r1' 'r2' 'r3']]


In [163]:
#create a csv file with column and row headers
new_array = np.array([[1.89, 2.23, 3.35], [5.30, 7.75, 5.65], [1.89, 3.01, 4.56]])
#round off new array
new_array = np.round(new_array, decimals=1)
#add column header
column_header= ['col1','col2','col3']
##ad row header
row_header = ['----'],['row1'], ['row2'], ['row3']
#stacking rows and column header ot the array
array_with_header = np.vstack([column_header, new_array])

final_array = np.hstack([row_header, array_with_header])

np.savetxt('myfile.csv', final_array, delimiter=',', fmt='%s')